In [1]:
import pandas as pd

In [2]:
gaze_df = pd.read_csv('Raw_data/sel-att-data-185-188-May26-2023.csv')
gaze_df

,expID,subID,threshold,label#,onset,offset,learned,pretrained,roi_at_label_onset,roi_at_label_onset_long,...,uniqueObjectsVisitedCount_long,skewed,skewed_long,correctness,correctness_long,preLabelWindowCount,preLabelWindowCount_long,trial,labelingInstance,SubjObjectGazeProp
0,185,18511,0.7,10,2.25,4.50,1,0,5,5,...,2,1,1,2,2,2,2,1,1,0.905781
1,185,18511,0.7,5,4.50,6.75,0,0,0,0,...,3,0,0,0,0,1,1,1,1,0.905781
2,185,18511,0.7,7,6.75,9.00,1,2,10,10,...,4,0,0,0,0,1,1,1,1,0.905781
3,185,18511,0.7,2,9.00,11.25,1,1,5,5,...,4,0,0,1,1,1,1,1,1,0.905781
4,185,18511,0.7,14,13.70,15.95,0,0,14,14,...,2,1,1,2,2,1,1,2,1,0.905781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26239,188,18872,0.7,10,295.25,297.50,1,0,10,10,...,1,1,1,2,2,1,1,26,6,0.895003
26240,188,18872,0.7,11,299.95,302.20,1,3,7,7,...,3,1,1,2,2,1,1,27,6,0.895003
26241,188,18872,0.7,17,302.20,304.45,1,0,11,11,...,3,0,0,2,2,1,1,27,6,0.895003
26242,188,18872,0.7,7,304.45,306.70,1,2,8,8,...,2,1,1,0,0,1,1,27,6,0.895003
26243,188,18872,0.7,8,306.70,308.95,1,0,8,8,...,1,1,1,2,2,1,1,27,6,0.895003

In [3]:
def prep_data():
    
    gaze_df = pd.read_csv('Raw_data/sel-att-data-185-188-May26-2023.csv')
    gaze_df['subID'] = gaze_df['subID'].astype('string')

    gaze_df['subject'] = gaze_df['subID'].str[-2:]
    gaze_df['subID'] = gaze_df['subID'].astype('string')
    
    gaze_df.sort_values(by=['subject','trial'],inplace=True)
    gaze_df.pop('subject')

    return gaze_df

In [10]:
def get_trial(*args):
    gaze_trial = prep_data()
        
    columns = ['subID','expID','trial','pretrained','learned']
    
    for arg in args:
        try:
            gaze_trial[arg]
        except:
            print(f'no column named \"{arg}\"')
        else:
            if arg not in columns:
                columns.append(arg)
                
    gaze_trial.reset_index(inplace=True,drop=True)
    
    return gaze_trial[columns]

In [11]:
get_trial('threshold','onset')

       subID  expID  trial  pretrained  learned  threshold   onset
0      18511    185      1           0        1        0.7    2.25
1      18511    185      1           0        0        0.7    4.50
2      18511    185      1           2        1        0.7    6.75
3      18511    185      1           1        1        0.7    9.00
4      18611    186      1           0        1        0.7    2.25
...      ...    ...    ...         ...      ...        ...     ...
26239  18772    187     27           0        1        0.7  306.70
26240  18872    188     27           3        1        0.7  299.95
26241  18872    188     27           0        1        0.7  302.20
26242  18872    188     27           2        1        0.7  304.45
26243  18872    188     27           0        1        0.7  306.70

[26244 rows x 7 columns]